## Config page of my jekyll website on Github.
name: Jaime de la Fuente
###theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: Jaime de la Fuente
description: wassup

# This needs to be added for seo and also for Github Pages compilation
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache


# Configuring the sidebar
#sidebar:
#nav: "sidebar"

# Set the skin (version of the theme in terms of colors and contrasts)
skin: "dark"
