## Config page of my jekyll website on Github.
name: Jaime de la Fuente
###theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
#title: Jaime de la Fuente

# Set the skin
minimal_mistakes_skin: "neon"  #, "dark", "dirt", "neon", "mint", "plum", "sunrise"

# This needs to be added for seo and also for Github Pages compilation
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
